#!/bin/sh
sudo su root

apt update && yes | DEBIAN_FRONTEND=noninteractive apt upgrade
yes | apt install python3-pip git build-essential libssl-dev libffi-dev python3-dev libwebp-dev libjpeg-dev libtiff-dev libopenjp2-7-dev zlib1g-dev knot-dnsutils resolvconf protobuf-compiler libprotobuf-dev
wget https://secure.nic.cz/files/knot-resolver/knot-resolver-release.deb
sudo dpkg -i knot-resolver-release.deb
sudo apt install -y knot-resolver
systemctl enable --now kresd@{1..2}.service
systemctl disable systemd-resolved

echo 'CAH_NICKNAME="Caricature, Inc"' >> /etc/environment

adduser --system --group --shell /bin/bash crawl
echo 'crawl     ALL=(ALL) NOPASSWD:ALL' >> /etc/sudoers

touch /home/crawl/worker-reset.sh
chmod 0744 /home/crawl/worker-reset.sh
echo '#!/bin/bash' >> /home/crawl/worker-reset.sh
echo '# Updates and resets the worker via SSH command' >> /home/crawl/worker-reset.sh
echo 'rm -rf /home/crawl/*.tar.gz' >> /home/crawl/worker-reset.sh
echo 'cd /home/crawl/crawlingathome-gpu-hcloud' >> /home/crawl/worker-reset.sh
echo 'git pull' >> /home/crawl/worker-reset.sh
echo 'systemctl restart crawl' >> /home/crawl/worker-reset.sh

echo "* soft     nproc          65535 " >> /etc/security/limits.conf
echo "* hard     nproc          65535 " >> /etc/security/limits.conf
echo "* soft     nofile         65535" >> /etc/security/limits.conf
echo "* hard     nofile         65535" >> /etc/security/limits.conf
echo "root soft     nproc          65535 " >> /etc/security/limits.conf
echo "root hard     nproc          65535 " >> /etc/security/limits.conf
echo "root soft     nofile         65535" >> /etc/security/limits.conf
echo "root hard     nofile         65535" >> /etc/security/limits.conf
echo "session required pam_limits.so" >> /etc/pam.d/common-session
echo "fs.file-max = 2097152" >> /etc/sysctl.conf

echo "[Unit]" >> /etc/systemd/system/crawl.service
echo "After=network.service" >> /etc/systemd/system/crawl.service
echo "Description=Crawling @ Home" >> /etc/systemd/system/crawl.service
echo "[Service]" >> /etc/systemd/system/crawl.service
echo "Type=simple" >> /etc/systemd/system/crawl.service
echo "LimitNOFILE=2097152" >> /etc/systemd/system/crawl.service
echo "WorkingDirectory=/home/crawl" >> /etc/systemd/system/crawl.service
echo "ExecStart=/home/crawl/crawl.sh" >> /etc/systemd/system/crawl.service
echo "EnvironmentFile=/etc/environment" >> /etc/systemd/system/crawl.service
echo "User=crawl" >> /etc/systemd/system/crawl.service
echo "Nice=10" >> /etc/systemd/system/crawl.service
echo "[Install]" >> /etc/systemd/system/crawl.service
echo "WantedBy=multi-user.target" >> /etc/systemd/system/crawl.service
chmod 664 /etc/systemd/system/crawl.service

systemctl daemon-reload
systemctl enable crawl.service

touch /home/crawl/crawl.sh
echo '#!/bin/bash' >> /home/crawl/crawl.sh
echo "while true" >> /home/crawl/crawl.sh
echo "do" >> /home/crawl/crawl.sh
echo "python3 -u /home/crawl/crawlingathome-gpu-hcloud/worker.py >> /home/crawl/crawl.log 2>&1" >> /home/crawl/crawl.sh
echo "sleep 1" >> /home/crawl/crawl.sh
echo "done" >> /home/crawl/crawl.sh
chmod 744 /home/crawl/crawl.sh
mkdir /home/crawl/.ssh
echo 'ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAACAQC0Ff0RcDRafX/VyxYJTeMWJrJGHIKvAvIG+nUmUR73iQFcwF7JP8FucLO0baVIPb029DI469SOZJWh6FTwt5T+IT5jm0UDAs2gwYClS+tRbohr27kXoILhlugFiCor4TD0mMhBTKme4RPLlcbLYaZq4r7Rep0rbWn46f3Gma2fDXgpy3v1JZBa30yHxQVO+s2UjbqPk9RcsWNQ7oap36yGrVb6Bc8ucwAM6pGTdJMQBZoTj0tgI/b9cSgKO1JRyUTt6HhuW+DDfrOuZPJLqOq0f5sNV0gD+89K9zNEtZeO+bpQuZvf+cwhb10XQc4t0Yd8EsyhxSbWbdvn6Utb9yQwmk7ThJkxLLLmDp5LtClOvp6PTFUooDjj3DgFfD8ZBK+sckwu1TPAKa8Y8jU+q4GfF5abAej5rXObVjVcKHsziBSsSG6yViVtoFAvqh0dYfM/Ujz7dj6KtfRs67J5X+8CJvvKokRZcjMs6neJNHoRll5t6K/uhQgKHvBRpFqL9kGS4hTEdJog47w9o8qmLTMYQ340ckEZkRh/c1lWu51wNycLW1iab40D2F/ymMihGxMo9AqHKoqE/cnh9SaZr1EGr7s4BhBnAvyOwHh2+sW5ndOenDOZ1wGbYbwVJznSG8I1tdlJzEjf2GuW1HZtxE/95yW0zlEQkue8mBfNUL+Q6Q== Generated by richa@RICHARD' >> /home/crawl/.ssh/authorized_keys

sed -i -e '/^\(#\|\)cache\.size/s/^.*$/cache\.size = 10000 \* MB/' /etc/knot-resolver/kresd.conf
echo "trust_anchors.remove('.')" >> /etc/knot-resolver/kresd.conf
echo "policy.add(policy.all(policy.FORWARD({'1.1.1.1'})))" >> /etc/knot-resolver/kresd.conf

cd /home/crawl

git clone https://github.com/rvencu/crawlingathome-gpu-hcloud
cd crawlingathome-gpu-hcloud
git clone "https://github.com/TheoCoombes/crawlingathome" crawlingathome_client
pip3 install -r crawlingathome_client/requirements.txt --no-cache-dir
pip3 install -r worker-requirements.txt --no-cache-dir
pip install random_user_agent

chown crawl:crawl -R /home/crawl/

sudo apt clean
sudo reboot
